[project]
name = "conda-forge-paths"
version = "0.1.0"
description = "Find which conda package provides a given file path"
authors = ["jaimergp <jaimergp@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

# [tasks]

[dependencies]
python = "3.12.*"
conda-package-streaming = ">=0.10.0"
conda-forge-metadata = ">=0.8"
tqdm = "*"

